

// Authentication Routes
export const AuthRoutes = {
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/login",
  REGISTER: "/register",
  FORGET_PASSWORD: "/forgot-password",
  VERIFY_OTP: "/verify-otp",
  RESET_PASSWORD: "/reset-password",
};

// Authenticated Routes
export const AuthenticatedRoutes = {
  USER_HOME: "/",
  TWOFA: "/setup-2fa",
  USER_DASHBOARD: "/dashboard",
  // ADMINTOPUP:"/admin-topup",
  WITHDRAWALBLOCK: "/block-withdrawal",
  USER_PROFILE: "/profile",
  BANK_DETAILS: "/bank-details",
  PACKAGE_REPORT: "/package-report",
  ConnectWallet: "/wallet-connect",
  // SELF_INCOME_REPORT: "/self-income-report",
  REFERRAL_INCOME_REPORT: "/referral-income-report",
  NEWS_AND_NOTIF: "/news-and-notif",
  SPIN_INCOME_REPORT: "/spin-income-report",
  LEVEL_INCOME_REPORT: "/levelIncome-history",
  STAKE_HISTORY: "/stake-investment-history",
  MATCHING_INCOME_REPORT: "/matching-income-report",
  ROI_INCOME_HISTORY: "/roi-history",
  ROYALTY_INCOME_REPORT: "/royalty-income-report",
  FUND_TRANSFER: "/fund-transfer",
  FUND_REQUEST: "/fund-request",
  FUND_REQUEST_HISTORY: "/fund-request-history",
  FUND_TRANSFER_HISTORY: "/fund-transfer-history",
  FUND_RECEIVE_HISTORY: "/fund-receive-history",
  TEAM_DIRECT: "/team-direct",
  TEAM_TREE: "/team-tree",
  WALLET: "/wallet",
  WITHDRAWAL_REPORT: "/withdrawal-report",
  OUR_PLANS: "/our-plans",
  TODAY_ROI: "/claim-today-roi",
  ADMIN_DASHBOARD: "/admin-dashboard",
  PENDING_USERS: "/pending-users",
  PENDING_FUND_REQUEST: "/pending-fund-request",
  PENDING_WITHDRAWAL_REQUEST: "/pending-withdrawal-request",
  APPROVED_USERS: "/approved-users",
  APPROVED_FUND_REQUEST: "/approved-fund-request",
  APPROVED_WITHDRAWAL_REQUEST: "/approved-withdrawal-request",
  REJECTED_USERS: "/rejected-users",
  REJECTED_FUND_REQUEST: "/rejected-fund-request",
  REJECTED_WITHDRAWAL_REQUEST: "/rejected-withdrawal-request",
  SUPPORT_RAISE_TICKET_HISTORY: "/support-raise-ticket-history",
  SUPPORT_RAISE_TICKET: "/support-raise-ticket",
  RAISE_TICKET_LIST: "/raise-ticket-list",
  ALL_USERS: "/all-users",
  PURCHASE_PLAN_HISTORY: "/purchase-plan-history",
  ROI_INCOME_REPORT: "/direct-referral-income-report",
  NEWS_AND_NOTIF_ADMIN: "/news-and-notif-admin",
  WITHDRAWAL_UPDATE: "/withdrawal-update",
  ACTIVE_USERS: "/active-users",
  DIRECT_REFERRAL_INCOME_REPORT: "/direct-referral-income-report",
  Wallet: "/wallet",
  ASSETS: "/assets",
  DAPP_WALLET: "/dappwallet",
  USDT_BEP: "/usdt-bep",
  USDT_TRC: "/usdt-trc",
  WITHDRAWAL: "/withdrawal",
  Activity: "/activity",
  HISTORY: "/history",
  AI_AGENT: "/ai-agent",
  AI_AGENT_DETAILS: "/ai-agent-details/:id",
  SUPPORT: "/support",
  ANNOUNCEMENTS: "/announcements",
  LEVEL_ACHIEVEMENT: "/level-achievement",
  USERAIRDROPALERT: "/user-airdrop-alert",
  MARKET: "/market",
  Admin_CommissionSetter: "/admin-commission-setter",
  REFERRAL_INCOME_PERCENT: "/referral-income-percent",
  LEVEL_INCOME_PERCENT: "/level-income-percent",
  AIRDROP_REFRELAL_INCOME: "/airdrop-referral-income",
  AIRDROP_LEVEL_INCOME: "/airdrop-level-income",
  AIRDROP_JOINING_INCOME: "/airdrop-joining-income",
  CHAT_HisTORY: "/chat-history",
  Ai_Agent_History: "/ai-agent-history",
  TRADE_HISTORY: "/trade-history",
  BOT_TRADE_HISTORY: "/bot-trade-history-details",
  BLOCK_UNBLOCK_USER: "/block-unblock-user",
  ADMIN_TOPUP: "/admin-topup",
  ADMIN_TOPUP_HISTORY: "/admin-topup-history",
  USER_INCOME_BLOCK: "/user-income-block",
  USER_PROFILE_EDIT: "/user-profile-edit",

};
